const express = require('express')
const bodyParser = require('body-parser')
const functions = require('firebase-functions')
const cors = require('cors')
const helmet = require('helmet')
const router = require('./src/router')

const app = express()
app.use(helmet())
app.use(bodyParser.json())
app.use(cors({origin: true}))
app.use(bodyParser.urlencoded({extended: true}))
app.use('/v1', router)
app.get('*', (req, res) => res.status(404).json({success: false}))

exports.api = functions.https.onRequest(app)
